//  crash3d - 3d visualization of sessions generated by crash
//  Copyright (C) 2016  Dag Robole
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "spectrum.h"
#include "conv_utils.h"
#include "rapidjson/document.h"
#include <fstream>

Spectrum::Spectrum()
{
}

Spectrum::~Spectrum()
{
}

bool Spectrum::load(const std::string &filename)
{
    namespace rap = rapidjson;

    std::ifstream fin(filename.c_str());
    std::string line, json;
    while(std::getline(fin, line))
        json += line;

    rap::Document doc;
    doc.Parse(json.c_str());
    if(!doc.HasMember("command"))
        return false;

    const rap::Value& args = doc["arguments"];
    if(!args.IsObject())
        return false;

    latitudeStart = from_string<double>(args["latitude_start"].GetString());
    latitudeEnd = from_string<double>(args["latitude_end"].GetString());
    longitudeStart = from_string<double>(args["longitude_start"].GetString());
    longitudeEnd = from_string<double>(args["longitude_end"].GetString());
    altitudeStart = from_string<double>(args["altitude_start"].GetString());
    altitudeEnd = from_string<double>(args["altitude_end"].GetString());

    return true;
}
